/**
 * Amar Ujala hyperlocal RSS districts — auto-generated by scripts/syncAmarUjalaDistrictFeeds.js
 * Last sync: 2026-06-23
 * @type {{ city: string, district: string, state: string, scope: string, rssSlug: string }[]}
 */
module.exports = [
  {
    "city": "Bhagalpur",
    "district": "Bhagalpur",
    "state": "Bihar",
    "scope": "bihar",
    "rssSlug": "bhagalpur"
  },
  {
    "city": "Darbhanga",
    "district": "Darbhanga",
    "state": "Bihar",
    "scope": "bihar",
    "rssSlug": "darbhanga"
  },
  {
    "city": "Gaya",
    "district": "Gaya",
    "state": "Bihar",
    "scope": "bihar",
    "rssSlug": "gaya"
  },
  {
    "city": "Kosi",
    "district": "Kosi",
    "state": "Bihar",
    "scope": "bihar",
    "rssSlug": "kosi"
  },
  {
    "city": "Munger",
    "district": "Munger",
    "state": "Bihar",
    "scope": "bihar",
    "rssSlug": "munger"
  },
  {
    "city": "Muzaffarpur",
    "district": "Muzaffarpur",
    "state": "Bihar",
    "scope": "bihar",
    "rssSlug": "muzaffarpur"
  },
  {
    "city": "Patna",
    "district": "Patna",
    "state": "Bihar",
    "scope": "bihar",
    "rssSlug": "patna"
  },
  {
    "city": "Purnea",
    "district": "Purnea",
    "state": "Bihar",
    "scope": "bihar",
    "rssSlug": "purnea"
  },
  {
    "city": "Saran",
    "district": "Saran",
    "state": "Bihar",
    "scope": "bihar",
    "rssSlug": "saran"
  },
  {
    "city": "Chandigarh",
    "district": "Chandigarh",
    "state": "Chandigarh",
    "scope": "punjab",
    "rssSlug": "chandigarh"
  },
  {
    "city": "Ambikapur",
    "district": "Ambikapur",
    "state": "Chhattisgarh",
    "scope": "north",
    "rssSlug": "ambikapur"
  },
  {
    "city": "Balod",
    "district": "Balod",
    "state": "Chhattisgarh",
    "scope": "north",
    "rssSlug": "balod"
  },
  {
    "city": "Bhatapara",
    "district": "Baloda Bazar",
    "state": "Chhattisgarh",
    "scope": "north",
    "rssSlug": "balodabazar-bhatapara"
  },
  {
    "city": "Bemetara",
    "district": "Bemetara",
    "state": "Chhattisgarh",
    "scope": "north",
    "rssSlug": "bemetara"
  },
  {
    "city": "Bijapur",
    "district": "Bijapur",
    "state": "Chhattisgarh",
    "scope": "north",
    "rssSlug": "bijapur"
  },
  {
    "city": "Bilaspur",
    "district": "Bilaspur",
    "state": "Chhattisgarh",
    "scope": "north",
    "rssSlug": "bilaspur-chhattisgarh"
  },
  {
    "city": "Dhamtari",
    "district": "Dhamtari",
    "state": "Chhattisgarh",
    "scope": "north",
    "rssSlug": "dhamtari"
  },
  {
    "city": "Bhilai",
    "district": "Durg",
    "state": "Chhattisgarh",
    "scope": "north",
    "rssSlug": "durg-bhilai"
  },
  {
    "city": "Pendra",
    "district": "Gaurela-Pendra-Marwahi",
    "state": "Chhattisgarh",
    "scope": "north",
    "rssSlug": "gorella-pendra-marwahi"
  },
  {
    "city": "Jagdalpur",
    "district": "Jagdalpur",
    "state": "Chhattisgarh",
    "scope": "north",
    "rssSlug": "jagdalpur"
  },
  {
    "city": "Janjgir",
    "district": "Janjgir-Champa",
    "state": "Chhattisgarh",
    "scope": "north",
    "rssSlug": "janjgir-champa"
  },
  {
    "city": "Kabirdham",
    "district": "Kabirdham",
    "state": "Chhattisgarh",
    "scope": "north",
    "rssSlug": "kabirdham"
  },
  {
    "city": "Kanker",
    "district": "Kanker",
    "state": "Chhattisgarh",
    "scope": "north",
    "rssSlug": "kanker"
  },
  {
    "city": "Korba",
    "district": "Korba",
    "state": "Chhattisgarh",
    "scope": "north",
    "rssSlug": "korba"
  },
  {
    "city": "Mahasamund",
    "district": "Mahasamund",
    "state": "Chhattisgarh",
    "scope": "north",
    "rssSlug": "mahasamund"
  },
  {
    "city": "Raigarh",
    "district": "Raigarh",
    "state": "Chhattisgarh",
    "scope": "north",
    "rssSlug": "raigarh"
  },
  {
    "city": "Raipur",
    "district": "Raipur",
    "state": "Chhattisgarh",
    "scope": "north",
    "rssSlug": "raipur"
  },
  {
    "city": "Delhi",
    "district": "Delhi",
    "state": "Delhi",
    "scope": "delhi",
    "rssSlug": "delhi"
  },
  {
    "city": "Ambala",
    "district": "Ambala",
    "state": "Haryana",
    "scope": "haryana",
    "rssSlug": "ambala"
  },
  {
    "city": "Bhiwani",
    "district": "Bhiwani",
    "state": "Haryana",
    "scope": "haryana",
    "rssSlug": "bhiwani"
  },
  {
    "city": "Charkhi Dadri",
    "district": "Charkhi Dadri",
    "state": "Haryana",
    "scope": "haryana",
    "rssSlug": "charkhi-dadri"
  },
  {
    "city": "Fatehabad",
    "district": "Fatehabad",
    "state": "Haryana",
    "scope": "haryana",
    "rssSlug": "fatehabad"
  },
  {
    "city": "Hisar",
    "district": "Hisar",
    "state": "Haryana",
    "scope": "haryana",
    "rssSlug": "hisar"
  },
  {
    "city": "Bahadurgarh",
    "district": "Jhajjar",
    "state": "Haryana",
    "scope": "haryana",
    "rssSlug": "jhajjar-bahadurgarh"
  },
  {
    "city": "Jind",
    "district": "Jind",
    "state": "Haryana",
    "scope": "haryana",
    "rssSlug": "jind"
  },
  {
    "city": "Kaithal",
    "district": "Kaithal",
    "state": "Haryana",
    "scope": "haryana",
    "rssSlug": "kaithal"
  },
  {
    "city": "Karnal",
    "district": "Karnal",
    "state": "Haryana",
    "scope": "haryana",
    "rssSlug": "karnal"
  },
  {
    "city": "Kurukshetra",
    "district": "Kurukshetra",
    "state": "Haryana",
    "scope": "haryana",
    "rssSlug": "kurukshetra"
  },
  {
    "city": "Narnaul",
    "district": "Mahendragarh",
    "state": "Haryana",
    "scope": "haryana",
    "rssSlug": "mahendragarh-narnaul"
  },
  {
    "city": "Palwal",
    "district": "Palwal",
    "state": "Haryana",
    "scope": "haryana",
    "rssSlug": "palwal"
  },
  {
    "city": "Panipat",
    "district": "Panipat",
    "state": "Haryana",
    "scope": "haryana",
    "rssSlug": "panipat"
  },
  {
    "city": "Rewari",
    "district": "Rewari",
    "state": "Haryana",
    "scope": "haryana",
    "rssSlug": "rewari"
  },
  {
    "city": "Rohtak",
    "district": "Rohtak",
    "state": "Haryana",
    "scope": "haryana",
    "rssSlug": "rohtak"
  },
  {
    "city": "Sirsa",
    "district": "Sirsa",
    "state": "Haryana",
    "scope": "haryana",
    "rssSlug": "sirsa"
  },
  {
    "city": "Sonipat",
    "district": "Sonipat",
    "state": "Haryana",
    "scope": "haryana",
    "rssSlug": "sonipat"
  },
  {
    "city": "Yamuna Nagar",
    "district": "Yamuna Nagar",
    "state": "Haryana",
    "scope": "haryana",
    "rssSlug": "yamuna-nagar"
  },
  {
    "city": "Bilaspur",
    "district": "Bilaspur",
    "state": "Himachal Pradesh",
    "scope": "north",
    "rssSlug": "bilaspur"
  },
  {
    "city": "Chamba",
    "district": "Chamba",
    "state": "Himachal Pradesh",
    "scope": "north",
    "rssSlug": "chamba"
  },
  {
    "city": "Hamirpur",
    "district": "Hamirpur",
    "state": "Himachal Pradesh",
    "scope": "north",
    "rssSlug": "hamirpur-hp"
  },
  {
    "city": "Kangra",
    "district": "Kangra",
    "state": "Himachal Pradesh",
    "scope": "north",
    "rssSlug": "kangra"
  },
  {
    "city": "Kullu",
    "district": "Kullu",
    "state": "Himachal Pradesh",
    "scope": "north",
    "rssSlug": "kullu"
  },
  {
    "city": "Mandi",
    "district": "Mandi",
    "state": "Himachal Pradesh",
    "scope": "north",
    "rssSlug": "mandi"
  },
  {
    "city": "Rampur Bushahr",
    "district": "Shimla",
    "state": "Himachal Pradesh",
    "scope": "north",
    "rssSlug": "rampur-bushahar"
  },
  {
    "city": "Sirmour",
    "district": "Sirmour",
    "state": "Himachal Pradesh",
    "scope": "north",
    "rssSlug": "sirmour"
  },
  {
    "city": "Solan",
    "district": "Solan",
    "state": "Himachal Pradesh",
    "scope": "north",
    "rssSlug": "solan"
  },
  {
    "city": "Una",
    "district": "Una",
    "state": "Himachal Pradesh",
    "scope": "north",
    "rssSlug": "una"
  },
  {
    "city": "Jammu",
    "district": "Jammu",
    "state": "Jammu and Kashmir",
    "scope": "north",
    "rssSlug": "jammu"
  },
  {
    "city": "Kathua",
    "district": "Kathua",
    "state": "Jammu and Kashmir",
    "scope": "north",
    "rssSlug": "kathua"
  },
  {
    "city": "Poonch",
    "district": "Poonch",
    "state": "Jammu and Kashmir",
    "scope": "north",
    "rssSlug": "poonch"
  },
  {
    "city": "Rajouri",
    "district": "Rajouri",
    "state": "Jammu and Kashmir",
    "scope": "north",
    "rssSlug": "rajouri"
  },
  {
    "city": "Srinagar",
    "district": "Srinagar",
    "state": "Jammu and Kashmir",
    "scope": "north",
    "rssSlug": "srinagar"
  },
  {
    "city": "Udhampur",
    "district": "Udhampur",
    "state": "Jammu and Kashmir",
    "scope": "north",
    "rssSlug": "udhampur"
  },
  {
    "city": "Agar Malwa",
    "district": "Agar Malwa",
    "state": "Madhya Pradesh",
    "scope": "north",
    "rssSlug": "agar-malwa"
  },
  {
    "city": "Ashoknagar",
    "district": "Ashoknagar",
    "state": "Madhya Pradesh",
    "scope": "north",
    "rssSlug": "ashoknagar"
  },
  {
    "city": "Balaghat",
    "district": "Balaghat",
    "state": "Madhya Pradesh",
    "scope": "north",
    "rssSlug": "balaghat"
  },
  {
    "city": "Barwani",
    "district": "Barwani",
    "state": "Madhya Pradesh",
    "scope": "north",
    "rssSlug": "barwani"
  },
  {
    "city": "Betul",
    "district": "Betul",
    "state": "Madhya Pradesh",
    "scope": "north",
    "rssSlug": "betul"
  },
  {
    "city": "Bhind",
    "district": "Bhind",
    "state": "Madhya Pradesh",
    "scope": "north",
    "rssSlug": "bhind"
  },
  {
    "city": "Bhopal",
    "district": "Bhopal",
    "state": "Madhya Pradesh",
    "scope": "north",
    "rssSlug": "bhopal"
  },
  {
    "city": "Chhatarpur",
    "district": "Chhatarpur",
    "state": "Madhya Pradesh",
    "scope": "north",
    "rssSlug": "chhatarpur"
  },
  {
    "city": "Damoh",
    "district": "Damoh",
    "state": "Madhya Pradesh",
    "scope": "north",
    "rssSlug": "damoh"
  },
  {
    "city": "Datia",
    "district": "Datia",
    "state": "Madhya Pradesh",
    "scope": "north",
    "rssSlug": "datia"
  },
  {
    "city": "Dewas",
    "district": "Dewas",
    "state": "Madhya Pradesh",
    "scope": "north",
    "rssSlug": "dewas"
  },
  {
    "city": "Dhar",
    "district": "Dhar",
    "state": "Madhya Pradesh",
    "scope": "north",
    "rssSlug": "dhar"
  },
  {
    "city": "Guna",
    "district": "Guna",
    "state": "Madhya Pradesh",
    "scope": "north",
    "rssSlug": "guna"
  },
  {
    "city": "Gwalior",
    "district": "Gwalior",
    "state": "Madhya Pradesh",
    "scope": "north",
    "rssSlug": "gwalior"
  },
  {
    "city": "Harda",
    "district": "Harda",
    "state": "Madhya Pradesh",
    "scope": "north",
    "rssSlug": "harda"
  },
  {
    "city": "Indore",
    "district": "Indore",
    "state": "Madhya Pradesh",
    "scope": "north",
    "rssSlug": "indore"
  },
  {
    "city": "Jabalpur",
    "district": "Jabalpur",
    "state": "Madhya Pradesh",
    "scope": "north",
    "rssSlug": "jabalpur"
  },
  {
    "city": "Jhabua",
    "district": "Jhabua",
    "state": "Madhya Pradesh",
    "scope": "north",
    "rssSlug": "jhabua"
  },
  {
    "city": "Khandwa",
    "district": "Khandwa",
    "state": "Madhya Pradesh",
    "scope": "north",
    "rssSlug": "khandwa"
  },
  {
    "city": "Khargone",
    "district": "Khargone",
    "state": "Madhya Pradesh",
    "scope": "north",
    "rssSlug": "khargone"
  },
  {
    "city": "Morena",
    "district": "Morena",
    "state": "Madhya Pradesh",
    "scope": "north",
    "rssSlug": "morena"
  },
  {
    "city": "Narmadapuram",
    "district": "Narmadapuram",
    "state": "Madhya Pradesh",
    "scope": "north",
    "rssSlug": "narmadapuram"
  },
  {
    "city": "Narsinghpur",
    "district": "Narsinghpur",
    "state": "Madhya Pradesh",
    "scope": "north",
    "rssSlug": "narsinghpur"
  },
  {
    "city": "Panna",
    "district": "Panna",
    "state": "Madhya Pradesh",
    "scope": "north",
    "rssSlug": "panna"
  },
  {
    "city": "Rajgarh",
    "district": "Rajgarh",
    "state": "Madhya Pradesh",
    "scope": "north",
    "rssSlug": "rajgarh"
  },
  {
    "city": "Ratlam",
    "district": "Ratlam",
    "state": "Madhya Pradesh",
    "scope": "north",
    "rssSlug": "ratlam"
  },
  {
    "city": "Sagar",
    "district": "Sagar",
    "state": "Madhya Pradesh",
    "scope": "north",
    "rssSlug": "sagar"
  },
  {
    "city": "Sehore",
    "district": "Sehore",
    "state": "Madhya Pradesh",
    "scope": "north",
    "rssSlug": "sehore"
  },
  {
    "city": "Seoni",
    "district": "Seoni",
    "state": "Madhya Pradesh",
    "scope": "north",
    "rssSlug": "seoni"
  },
  {
    "city": "Shajapur",
    "district": "Shajapur",
    "state": "Madhya Pradesh",
    "scope": "north",
    "rssSlug": "shajapur"
  },
  {
    "city": "Shivpuri",
    "district": "Shivpuri",
    "state": "Madhya Pradesh",
    "scope": "north",
    "rssSlug": "shivpuri"
  },
  {
    "city": "Sidhi",
    "district": "Sidhi",
    "state": "Madhya Pradesh",
    "scope": "north",
    "rssSlug": "sidhi"
  },
  {
    "city": "Tikamgarh",
    "district": "Tikamgarh",
    "state": "Madhya Pradesh",
    "scope": "north",
    "rssSlug": "tikamgarh"
  },
  {
    "city": "Ujjain",
    "district": "Ujjain",
    "state": "Madhya Pradesh",
    "scope": "north",
    "rssSlug": "ujjain"
  },
  {
    "city": "Umaria",
    "district": "Umaria",
    "state": "Madhya Pradesh",
    "scope": "north",
    "rssSlug": "umaria"
  },
  {
    "city": "Vidisha",
    "district": "Vidisha",
    "state": "Madhya Pradesh",
    "scope": "north",
    "rssSlug": "vidisha"
  },
  {
    "city": "Amritsar",
    "district": "Amritsar",
    "state": "Punjab",
    "scope": "punjab",
    "rssSlug": "amritsar"
  },
  {
    "city": "Jalandhar",
    "district": "Jalandhar",
    "state": "Punjab",
    "scope": "punjab",
    "rssSlug": "jalandhar"
  },
  {
    "city": "Ludhiana",
    "district": "Ludhiana",
    "state": "Punjab",
    "scope": "punjab",
    "rssSlug": "ludhiana"
  },
  {
    "city": "Patiala",
    "district": "Patiala",
    "state": "Punjab",
    "scope": "punjab",
    "rssSlug": "patiala"
  },
  {
    "city": "Ajmer",
    "district": "Ajmer",
    "state": "Rajasthan",
    "scope": "rajasthan",
    "rssSlug": "ajmer"
  },
  {
    "city": "Alwar",
    "district": "Alwar",
    "state": "Rajasthan",
    "scope": "rajasthan",
    "rssSlug": "alwar"
  },
  {
    "city": "Banswara",
    "district": "Banswara",
    "state": "Rajasthan",
    "scope": "rajasthan",
    "rssSlug": "banswara"
  },
  {
    "city": "Barmer",
    "district": "Barmer",
    "state": "Rajasthan",
    "scope": "rajasthan",
    "rssSlug": "barmer"
  },
  {
    "city": "Bharatpur",
    "district": "Bharatpur",
    "state": "Rajasthan",
    "scope": "rajasthan",
    "rssSlug": "bharatpur"
  },
  {
    "city": "Bhilwara",
    "district": "Bhilwara",
    "state": "Rajasthan",
    "scope": "rajasthan",
    "rssSlug": "bhilwara"
  },
  {
    "city": "Bikaner",
    "district": "Bikaner",
    "state": "Rajasthan",
    "scope": "rajasthan",
    "rssSlug": "bikaner"
  },
  {
    "city": "Bundi",
    "district": "Bundi",
    "state": "Rajasthan",
    "scope": "rajasthan",
    "rssSlug": "bundi"
  },
  {
    "city": "Chittorgarh",
    "district": "Chittorgarh",
    "state": "Rajasthan",
    "scope": "rajasthan",
    "rssSlug": "chittorgarh"
  },
  {
    "city": "Dausa",
    "district": "Dausa",
    "state": "Rajasthan",
    "scope": "rajasthan",
    "rssSlug": "dausa"
  },
  {
    "city": "Dholpur",
    "district": "Dholpur",
    "state": "Rajasthan",
    "scope": "rajasthan",
    "rssSlug": "dholpur"
  },
  {
    "city": "Hanumangarh",
    "district": "Hanumangarh",
    "state": "Rajasthan",
    "scope": "rajasthan",
    "rssSlug": "hanumangarh"
  },
  {
    "city": "Jaipur",
    "district": "Jaipur",
    "state": "Rajasthan",
    "scope": "rajasthan",
    "rssSlug": "jaipur"
  },
  {
    "city": "Jaisalmer",
    "district": "Jaisalmer",
    "state": "Rajasthan",
    "scope": "rajasthan",
    "rssSlug": "jaisalmer"
  },
  {
    "city": "Jalore",
    "district": "Jalore",
    "state": "Rajasthan",
    "scope": "rajasthan",
    "rssSlug": "jalore"
  },
  {
    "city": "Jhalawar",
    "district": "Jhalawar",
    "state": "Rajasthan",
    "scope": "rajasthan",
    "rssSlug": "jhalawar"
  },
  {
    "city": "Jhunjhunu",
    "district": "Jhunjhunu",
    "state": "Rajasthan",
    "scope": "rajasthan",
    "rssSlug": "jhunjhunu"
  },
  {
    "city": "Jodhpur",
    "district": "Jodhpur",
    "state": "Rajasthan",
    "scope": "rajasthan",
    "rssSlug": "jodhpur"
  },
  {
    "city": "Karauli",
    "district": "Karauli",
    "state": "Rajasthan",
    "scope": "rajasthan",
    "rssSlug": "karauli"
  },
  {
    "city": "Kota",
    "district": "Kota",
    "state": "Rajasthan",
    "scope": "rajasthan",
    "rssSlug": "kota"
  },
  {
    "city": "Nagaur",
    "district": "Nagaur",
    "state": "Rajasthan",
    "scope": "rajasthan",
    "rssSlug": "nagaur"
  },
  {
    "city": "Rajsamand",
    "district": "Rajsamand",
    "state": "Rajasthan",
    "scope": "rajasthan",
    "rssSlug": "rajsamand"
  },
  {
    "city": "Salumber",
    "district": "Salumber",
    "state": "Rajasthan",
    "scope": "rajasthan",
    "rssSlug": "salumber"
  },
  {
    "city": "Sikar",
    "district": "Sikar",
    "state": "Rajasthan",
    "scope": "rajasthan",
    "rssSlug": "sikar"
  },
  {
    "city": "Sirohi",
    "district": "Sirohi",
    "state": "Rajasthan",
    "scope": "rajasthan",
    "rssSlug": "sirohi"
  },
  {
    "city": "Sri Ganganagar",
    "district": "Sri Ganganagar",
    "state": "Rajasthan",
    "scope": "rajasthan",
    "rssSlug": "sri-ganganagar"
  },
  {
    "city": "Tonk",
    "district": "Tonk",
    "state": "Rajasthan",
    "scope": "rajasthan",
    "rssSlug": "tonk"
  },
  {
    "city": "Udaipur",
    "district": "Udaipur",
    "state": "Rajasthan",
    "scope": "rajasthan",
    "rssSlug": "udaipur"
  },
  {
    "city": "Agra",
    "district": "Agra",
    "state": "Uttar Pradesh",
    "scope": "up",
    "rssSlug": "agra"
  },
  {
    "city": "Aligarh",
    "district": "Aligarh",
    "state": "Uttar Pradesh",
    "scope": "up",
    "rssSlug": "aligarh"
  },
  {
    "city": "Ambedkar Nagar",
    "district": "Ambedkar Nagar",
    "state": "Uttar Pradesh",
    "scope": "up",
    "rssSlug": "ambedkar-nagar"
  },
  {
    "city": "Amethi",
    "district": "Amethi",
    "state": "Uttar Pradesh",
    "scope": "up",
    "rssSlug": "amethi"
  },
  {
    "city": "Amroha",
    "district": "Amroha",
    "state": "Uttar Pradesh",
    "scope": "up",
    "rssSlug": "amroha"
  },
  {
    "city": "Auraiya",
    "district": "Auraiya",
    "state": "Uttar Pradesh",
    "scope": "up",
    "rssSlug": "auraiya"
  },
  {
    "city": "Ayodhya",
    "district": "Ayodhya",
    "state": "Uttar Pradesh",
    "scope": "up",
    "rssSlug": "ayodhya"
  },
  {
    "city": "Azamgarh",
    "district": "Azamgarh",
    "state": "Uttar Pradesh",
    "scope": "up",
    "rssSlug": "azamgarh"
  },
  {
    "city": "Baghpat",
    "district": "Baghpat",
    "state": "Uttar Pradesh",
    "scope": "up",
    "rssSlug": "baghpat"
  },
  {
    "city": "Bahraich",
    "district": "Bahraich",
    "state": "Uttar Pradesh",
    "scope": "up",
    "rssSlug": "bahraich"
  },
  {
    "city": "Ballia",
    "district": "Ballia",
    "state": "Uttar Pradesh",
    "scope": "up",
    "rssSlug": "ballia"
  },
  {
    "city": "Balrampur",
    "district": "Balrampur",
    "state": "Uttar Pradesh",
    "scope": "up",
    "rssSlug": "balrampur"
  },
  {
    "city": "Banda",
    "district": "Banda",
    "state": "Uttar Pradesh",
    "scope": "up",
    "rssSlug": "banda"
  },
  {
    "city": "Barabanki",
    "district": "Barabanki",
    "state": "Uttar Pradesh",
    "scope": "up",
    "rssSlug": "barabanki"
  },
  {
    "city": "Bareilly",
    "district": "Bareilly",
    "state": "Uttar Pradesh",
    "scope": "up",
    "rssSlug": "bareilly"
  },
  {
    "city": "Basti",
    "district": "Basti",
    "state": "Uttar Pradesh",
    "scope": "up",
    "rssSlug": "basti"
  },
  {
    "city": "Bhadohi",
    "district": "Bhadohi",
    "state": "Uttar Pradesh",
    "scope": "up",
    "rssSlug": "bhadohi"
  },
  {
    "city": "Bijnor",
    "district": "Bijnor",
    "state": "Uttar Pradesh",
    "scope": "up",
    "rssSlug": "bijnor"
  },
  {
    "city": "Budaun",
    "district": "Budaun",
    "state": "Uttar Pradesh",
    "scope": "up",
    "rssSlug": "budaun"
  },
  {
    "city": "Bulandshahr",
    "district": "Bulandshahr",
    "state": "Uttar Pradesh",
    "scope": "up",
    "rssSlug": "bulandshahr"
  },
  {
    "city": "Chandauli",
    "district": "Chandauli",
    "state": "Uttar Pradesh",
    "scope": "up",
    "rssSlug": "chandauli"
  },
  {
    "city": "Chitrakoot",
    "district": "Chitrakoot",
    "state": "Uttar Pradesh",
    "scope": "up",
    "rssSlug": "chitrakoot"
  },
  {
    "city": "Deoria",
    "district": "Deoria",
    "state": "Uttar Pradesh",
    "scope": "up",
    "rssSlug": "deoria"
  },
  {
    "city": "Etah",
    "district": "Etah",
    "state": "Uttar Pradesh",
    "scope": "up",
    "rssSlug": "etah"
  },
  {
    "city": "Etawah",
    "district": "Etawah",
    "state": "Uttar Pradesh",
    "scope": "up",
    "rssSlug": "etawah"
  },
  {
    "city": "Farrukhabad",
    "district": "Farrukhabad",
    "state": "Uttar Pradesh",
    "scope": "up",
    "rssSlug": "farrukhabad"
  },
  {
    "city": "Fatehpur",
    "district": "Fatehpur",
    "state": "Uttar Pradesh",
    "scope": "up",
    "rssSlug": "fatehpur"
  },
  {
    "city": "Firozabad",
    "district": "Firozabad",
    "state": "Uttar Pradesh",
    "scope": "up",
    "rssSlug": "firozabad"
  },
  {
    "city": "Noida",
    "district": "Gautam Buddha Nagar",
    "state": "Uttar Pradesh",
    "scope": "up",
    "rssSlug": "noida"
  },
  {
    "city": "Ghatampur",
    "district": "Ghatampur",
    "state": "Uttar Pradesh",
    "scope": "up",
    "rssSlug": "ghatampur"
  },
  {
    "city": "Ghaziabad",
    "district": "Ghaziabad",
    "state": "Uttar Pradesh",
    "scope": "up",
    "rssSlug": "ghaziabad"
  },
  {
    "city": "Ghazipur",
    "district": "Ghazipur",
    "state": "Uttar Pradesh",
    "scope": "up",
    "rssSlug": "ghazipur"
  },
  {
    "city": "Gonda",
    "district": "Gonda",
    "state": "Uttar Pradesh",
    "scope": "up",
    "rssSlug": "gonda"
  },
  {
    "city": "Gorakhpur",
    "district": "Gorakhpur",
    "state": "Uttar Pradesh",
    "scope": "up",
    "rssSlug": "gorakhpur"
  },
  {
    "city": "Hamirpur",
    "district": "Hamirpur",
    "state": "Uttar Pradesh",
    "scope": "up",
    "rssSlug": "hamirpur"
  },
  {
    "city": "Hapur",
    "district": "Hapur",
    "state": "Uttar Pradesh",
    "scope": "up",
    "rssSlug": "hapur"
  },
  {
    "city": "Hardoi",
    "district": "Hardoi",
    "state": "Uttar Pradesh",
    "scope": "up",
    "rssSlug": "hardoi"
  },
  {
    "city": "Hathras",
    "district": "Hathras",
    "state": "Uttar Pradesh",
    "scope": "up",
    "rssSlug": "hathras"
  },
  {
    "city": "Jalaun",
    "district": "Jalaun",
    "state": "Uttar Pradesh",
    "scope": "up",
    "rssSlug": "jalaun"
  },
  {
    "city": "Jaunpur",
    "district": "Jaunpur",
    "state": "Uttar Pradesh",
    "scope": "up",
    "rssSlug": "jaunpur"
  },
  {
    "city": "Jhansi",
    "district": "Jhansi",
    "state": "Uttar Pradesh",
    "scope": "up",
    "rssSlug": "jhansi"
  },
  {
    "city": "Kannauj",
    "district": "Kannauj",
    "state": "Uttar Pradesh",
    "scope": "up",
    "rssSlug": "kannauj"
  },
  {
    "city": "Kanpur",
    "district": "Kanpur",
    "state": "Uttar Pradesh",
    "scope": "up",
    "rssSlug": "kanpur"
  },
  {
    "city": "Kaushambi",
    "district": "Kaushambi",
    "state": "Uttar Pradesh",
    "scope": "up",
    "rssSlug": "kaushambi"
  },
  {
    "city": "Kushinagar",
    "district": "Kushinagar",
    "state": "Uttar Pradesh",
    "scope": "up",
    "rssSlug": "kushinagar"
  },
  {
    "city": "Lakhimpur",
    "district": "Lakhimpur Kheri",
    "state": "Uttar Pradesh",
    "scope": "up",
    "rssSlug": "lakhimpur-kheri"
  },
  {
    "city": "Lalitpur",
    "district": "Lalitpur",
    "state": "Uttar Pradesh",
    "scope": "up",
    "rssSlug": "lalitpur"
  },
  {
    "city": "Lucknow",
    "district": "Lucknow",
    "state": "Uttar Pradesh",
    "scope": "up",
    "rssSlug": "lucknow"
  },
  {
    "city": "Maharajganj",
    "district": "Maharajganj",
    "state": "Uttar Pradesh",
    "scope": "up",
    "rssSlug": "maharajganj"
  },
  {
    "city": "Mahoba",
    "district": "Mahoba",
    "state": "Uttar Pradesh",
    "scope": "up",
    "rssSlug": "mahoba"
  },
  {
    "city": "Mainpuri",
    "district": "Mainpuri",
    "state": "Uttar Pradesh",
    "scope": "up",
    "rssSlug": "mainpuri"
  },
  {
    "city": "Mathura",
    "district": "Mathura",
    "state": "Uttar Pradesh",
    "scope": "up",
    "rssSlug": "mathura"
  },
  {
    "city": "Mau",
    "district": "Mau",
    "state": "Uttar Pradesh",
    "scope": "up",
    "rssSlug": "mau"
  },
  {
    "city": "Meerut",
    "district": "Meerut",
    "state": "Uttar Pradesh",
    "scope": "up",
    "rssSlug": "meerut"
  },
  {
    "city": "Mirzapur",
    "district": "Mirzapur",
    "state": "Uttar Pradesh",
    "scope": "up",
    "rssSlug": "mirzapur"
  },
  {
    "city": "Moradabad",
    "district": "Moradabad",
    "state": "Uttar Pradesh",
    "scope": "up",
    "rssSlug": "moradabad"
  },
  {
    "city": "Muzaffarnagar",
    "district": "Muzaffarnagar",
    "state": "Uttar Pradesh",
    "scope": "up",
    "rssSlug": "muzaffarnagar"
  },
  {
    "city": "Pilibhit",
    "district": "Pilibhit",
    "state": "Uttar Pradesh",
    "scope": "up",
    "rssSlug": "pilibhit"
  },
  {
    "city": "Pratapgarh",
    "district": "Pratapgarh",
    "state": "Uttar Pradesh",
    "scope": "up",
    "rssSlug": "pratapgarh"
  },
  {
    "city": "Prayagraj",
    "district": "Prayagraj",
    "state": "Uttar Pradesh",
    "scope": "up",
    "rssSlug": "allahabad"
  },
  {
    "city": "Raebareli",
    "district": "Raebareli",
    "state": "Uttar Pradesh",
    "scope": "up",
    "rssSlug": "raebareli"
  },
  {
    "city": "Rampur",
    "district": "Rampur",
    "state": "Uttar Pradesh",
    "scope": "up",
    "rssSlug": "rampur"
  },
  {
    "city": "Saharanpur",
    "district": "Saharanpur",
    "state": "Uttar Pradesh",
    "scope": "up",
    "rssSlug": "saharanpur"
  },
  {
    "city": "Sambhal",
    "district": "Sambhal",
    "state": "Uttar Pradesh",
    "scope": "up",
    "rssSlug": "sambhal"
  },
  {
    "city": "Khalilabad",
    "district": "Sant Kabir Nagar",
    "state": "Uttar Pradesh",
    "scope": "up",
    "rssSlug": "sant-kabir-nagar"
  },
  {
    "city": "Shahjahanpur",
    "district": "Shahjahanpur",
    "state": "Uttar Pradesh",
    "scope": "up",
    "rssSlug": "shahjahanpur"
  },
  {
    "city": "Shamli",
    "district": "Shamli",
    "state": "Uttar Pradesh",
    "scope": "up",
    "rssSlug": "shamli"
  },
  {
    "city": "Shravasti",
    "district": "Shravasti",
    "state": "Uttar Pradesh",
    "scope": "up",
    "rssSlug": "shravasti"
  },
  {
    "city": "Siddharthnagar",
    "district": "Siddharthnagar",
    "state": "Uttar Pradesh",
    "scope": "up",
    "rssSlug": "siddharthnagar"
  },
  {
    "city": "Sitapur",
    "district": "Sitapur",
    "state": "Uttar Pradesh",
    "scope": "up",
    "rssSlug": "sitapur"
  },
  {
    "city": "Sonebhadra",
    "district": "Sonebhadra",
    "state": "Uttar Pradesh",
    "scope": "up",
    "rssSlug": "sonebhadra"
  },
  {
    "city": "Sultanpur",
    "district": "Sultanpur",
    "state": "Uttar Pradesh",
    "scope": "up",
    "rssSlug": "sultanpur"
  },
  {
    "city": "Unnao",
    "district": "Unnao",
    "state": "Uttar Pradesh",
    "scope": "up",
    "rssSlug": "unnao"
  },
  {
    "city": "Varanasi",
    "district": "Varanasi",
    "state": "Uttar Pradesh",
    "scope": "up",
    "rssSlug": "varanasi"
  },
  {
    "city": "Almora",
    "district": "Almora",
    "state": "Uttarakhand",
    "scope": "north",
    "rssSlug": "almora"
  },
  {
    "city": "Bageshwar",
    "district": "Bageshwar",
    "state": "Uttarakhand",
    "scope": "north",
    "rssSlug": "bageshwar"
  },
  {
    "city": "Chamoli",
    "district": "Chamoli",
    "state": "Uttarakhand",
    "scope": "north",
    "rssSlug": "chamoli"
  },
  {
    "city": "Champawat",
    "district": "Champawat",
    "state": "Uttarakhand",
    "scope": "north",
    "rssSlug": "champawat"
  },
  {
    "city": "Dehradun",
    "district": "Dehradun",
    "state": "Uttarakhand",
    "scope": "north",
    "rssSlug": "dehradun"
  },
  {
    "city": "Haridwar",
    "district": "Haridwar",
    "state": "Uttarakhand",
    "scope": "north",
    "rssSlug": "haridwar"
  },
  {
    "city": "Kotdwar",
    "district": "Kotdwar",
    "state": "Uttarakhand",
    "scope": "north",
    "rssSlug": "kotdwar"
  },
  {
    "city": "Nainital",
    "district": "Nainital",
    "state": "Uttarakhand",
    "scope": "north",
    "rssSlug": "nainital"
  },
  {
    "city": "Pauri",
    "district": "Pauri",
    "state": "Uttarakhand",
    "scope": "north",
    "rssSlug": "pauri"
  },
  {
    "city": "Pithoragarh",
    "district": "Pithoragarh",
    "state": "Uttarakhand",
    "scope": "north",
    "rssSlug": "pithoragarh"
  },
  {
    "city": "Rishikesh",
    "district": "Rishikesh",
    "state": "Uttarakhand",
    "scope": "north",
    "rssSlug": "rishikesh"
  },
  {
    "city": "Roorkee",
    "district": "Roorkee",
    "state": "Uttarakhand",
    "scope": "north",
    "rssSlug": "roorkee"
  },
  {
    "city": "Rudraprayag",
    "district": "Rudraprayag",
    "state": "Uttarakhand",
    "scope": "north",
    "rssSlug": "rudraprayag"
  },
  {
    "city": "Tehri",
    "district": "Tehri",
    "state": "Uttarakhand",
    "scope": "north",
    "rssSlug": "tehri"
  },
  {
    "city": "Haldwani",
    "district": "Udham Singh Nagar",
    "state": "Uttarakhand",
    "scope": "north",
    "rssSlug": "udham-singh-nagar"
  },
  {
    "city": "Uttarkashi",
    "district": "Uttarkashi",
    "state": "Uttarakhand",
    "scope": "north",
    "rssSlug": "uttarkashi"
  }
];
